Removed unnecessary composer symlinks (#61)
badges/poser pull request #62
Opened 2020-10-25 13:41 UTC by GregOriol

These are generated by composer when installing the vendors, they should not be commited to the repository

2020-10-25 14:55 UTC, garak commented
IMO we should ignore bin directory (possibly whitelisting poser script)

2020-10-25 15:00 UTC, GregOriol commented
As I wrote in #61, I think the symlinks should be left in vendor/bin/ but I don't have enough knowledge of this project and why/how the bin folder is used to make such a change..

2020-10-25 15:32 UTC, garak commented
Probably vendor/bin is not standard (or not standard enough), while bin is actually standard

2020-10-26 09:32 UTC, GregOriol commented
vendor/bin is the default with composer, and it is used by most projects
bin should be only for the binaries from the current project

2020-10-26 09:38 UTC, garak commented
> vendor/bin is the default with composer, and it is used by most projects

Default does not imply a standard. You can configure your bin path (as we do) and composer provides a default only because it can't do assumptions on projects directory structure.

> bin should be only for the binaries from the current project

As already mentioned, it depends on composer configuration and using bin for non-project binaries is perfectly fine.

2020-10-26 09:40 UTC, GregOriol commented
Let's agree to disagree, but just don't commit those generated symlinks as this PR suggests

2020-10-26 09:52 UTC, garak commented
For me it's OK to remove such files from repository.
I'm just asking to also add bin dir to .gitignore, to avoid re-adding such files by mistake.

2020-10-26 10:06 UTC, garak requested changes

2020-10-26 10:06 UTC, garak commented on .gitignore
> +/bin/php-parse
This is not future-proof: if a new binary is added, we would be forced to add it here as well.
It would be better:
/bin/*
!/bin/poser

2020-10-26 10:14 UTC, garak approved these changes

2020-10-26 10:25 UTC, JellyBellyDev commented
@GregOriol good works! 
Please can you update che changelog file?

2020-10-26 10:27 UTC, GregOriol commented
@JellyBellyDev What would you want to write there? this is just cleaning the repository by removing some symlinks that are auto-generated, it doesn't change the project in any way.

2020-10-26 10:33 UTC, JellyBellyDev commented
> @JellyBellyDev What would you want to write there? this is just cleaning the repository by removing some symlinks that are auto-generated, it doesn't change the project in any way.

```
## [v2.0.2] - 2020-10-26

### Fixed
* add to `.gitignore` and removed unnecessary composer symlinks from `bin` dir 
```

WDYT?

2020-10-26 13:04 UTC, JellyBellyDev approved these changes
LGTM

2020-10-26 13:04 UTC, merged