Implement SvgTextSizeCalculator
badges/poser pull request #97
Opened 2023-10-11 21:08 UTC by antonkomarev

- Resolves #96

This is only the first step towards stopping using GD for icon rendering. To completely remove the GD dependency, we need to make backward incompatible changes.

This PR introduces new SvgTextSizeCalculator class which will allow us to make proof of concept in a safe manner. In a future major versions we could define it as default fallback calculator.

Calculate badge width using GD (default):
```php
$this->poser = new Poser([
    new SvgPlasticRender(),
    new SvgFlatRender(),
    new SvgFlatSquareRender(),
    new SvgForTheBadgeRenderer(),
]);
```

Calculate badge width using SVG (new):
```php
$this->poser = new Poser([
    new SvgPlasticRender(new SvgTextSizeCalculator()),
    new SvgFlatRender(new SvgTextSizeCalculator()),
    new SvgFlatSquareRender(new SvgTextSizeCalculator()),
    new SvgForTheBadgeRenderer(null, new SvgTextSizeCalculator()),
]);
```

Note: `SvgForTheBadgeRenderer` using its own class to compute text width using EasySVG (where I got an inspiration), but it using GD too because of the parent method call. So to avoid using GD you should provide new calculator implementation as second argument.

2023-10-11 21:33 UTC, antonkomarev commented
I'm going to review this code in the coming days, maybe it will be slightly modified. I really appreciate your feedback.

2023-10-13 08:20 UTC, garak requested changes
The code is OK for me, but it needs to be tested

2023-10-13 09:04 UTC, antonkomarev commented
I'm working on a new more cleaner implementation. Will return when it will be done.

2023-10-16 19:55 UTC, antonkomarev commented
@garak I've reworked this PR. All the logic of parsing SVG fonts and unicode characters (code points) extracted to separated unit tested packages:
- https://github.com/cybercog/php-svg-font
- https://github.com/cybercog/php-unicode

If you are OK with such solution I will continue to work towards this implementation.

Things to do:
- Cover with high level tests
- Tweak API of reading fonts

2023-10-16 21:39 UTC, antonkomarev commented
I have one question about GD calculator. There is a code:
```php
public function calculateWidth(string $text, int $size = self::TEXT_SIZE): float
{
    $size = $this->convertToPt($size);
    $box  = \imagettfbbox($size, 0, $this->fontPath, $text);

    return \round(\abs($box[2] - $box[0]) + self::SHIELD_PADDING_EXTERNAL + self::SHIELD_PADDING_INTERNAL, 1);
}

private function convertToPt(int $pixels): float
{
    return \round($pixels * 0.75, 1);
}
```

Why do we decreasing font size using `round($pixels * 0.75, 1)`?

2024-01-04 13:25 UTC, antonkomarev commented
Tests failing on code style. Same as in #101. It looks like CS Fixer issue and need to wait a fix.

2024-01-04 13:26 UTC, antonkomarev commented
> The code is OK for me, but it needs to be tested

@garak I wrote tests for the new SvgTextCalculator and for GdTextCalculator (they were missing).

2024-01-05 13:26 UTC, garak commented
> Tests are failing on code style. Same as in #101. It looks like CS Fixer issue, need fix it and re-run here.

I guess you can easily fix them. If you want to save time, my advice is to run php-cs-fixer on your local environment before pushing your commit.

2024-01-05 13:58 UTC, antonkomarev commented
@garak what part are you talking about? CS fails on infrastructure code, not committed one.

2024-01-05 14:07 UTC, garak commented
This part https://github.com/badges/poser/blob/master/.github/workflows/php.yml#L45

2024-01-05 14:11 UTC, JellyBellyDev commented
I'm fixing it here: https://github.com/badges/poser/pull/102

2024-01-05 14:15 UTC, JellyBellyDev commented
Please rebase! ;)

2024-01-05 14:17 UTC, garak commented
> I'm fixing it here: #102

but you fixed the symptom, not the problem itself :-(

2024-01-05 18:24 UTC, antonkomarev commented
@garak @JellyBellyDev rebased, ready for review

2024-01-05 18:30 UTC, antonkomarev commented
> > I'm fixing it here: #102
> 
> but you fixed the symptom, not the problem itself :-(

it is good as temporary solution, but later could be changed as well

2024-01-06 10:29 UTC, garak approved these changes

2024-01-06 18:14 UTC, merged

2024-01-06 18:15 UTC, antonkomarev commented
@garak @JellyBellyDev who can make minor release?

2024-01-07 11:55 UTC, JellyBellyDev commented
Done! 😉

2024-01-07 16:50 UTC, antonkomarev commented
@JellyBellyDev release is not appeared in Packagist: https://packagist.org/packages/badges/poser

2024-01-07 16:54 UTC, JellyBellyDev commented
Now yes! 👍🏻

2024-01-08 08:44 UTC, JellyBellyDev commented
I always forget that I don't have the privileges to set the package self-update hook on packagist and with each release I have to update it manually